// Independent state/timer regression checks. Browser/layout checks run separately.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
function app(saved={},options={}) {
 let now=0, sequence=0; const timers=new Map(), nodes=new Map(), listeners=new Map();
 function node(id) { if(!nodes.has(id)) { const classes=new Set(), attributes=new Map(); const element={id,style:{setProperty(k,v){this[k]=v;}},dataset:{},children:[],value:id==='teethSlider'?'15':'',textContent:'',innerHTML:'',disabled:false,
 classList:{replace(a,b){const had=classes.delete(a);if(had)classes.add(b);return had;},add:(...cs)=>cs.forEach(c=>classes.add(c)),remove:(...cs)=>cs.forEach(c=>classes.delete(c)),contains:c=>classes.has(c),toggle(c,force){if(force??!classes.has(c)){classes.add(c);return true;}classes.delete(c);return false;}},
 setAttribute:(k,v)=>attributes.set(k,String(v)),getAttribute:k=>attributes.get(k),removeAttribute:k=>attributes.delete(k),
 querySelector:()=>node(id+'-child'),querySelectorAll:()=>[],appendChild(child){this.children.push(child);child.parentNode=this;return child;},append(child){this.appendChild(child);},replaceChildren(...children){this.children=children;},remove(){this.removed=true;},
 addEventListener(type,fn){listeners.set(id+':'+type,fn);},setPointerCapture(){},releasePointerCapture(){},hasPointerCapture(){return true;},getBoundingClientRect:()=>({left:0,top:0,width:360,height:480,right:360,bottom:480}),focus(){}};nodes.set(id,element); } return nodes.get(id); }
 const screens=['leaderboard','score-record','setup','lobby','croc','reaction','cards','finger','plo','elim','result'].map(x=>node('screen-'+x));
 const localStorage={getItem:k=>saved[k]??null,setItem:(k,v)=>saved[k]=v};
 const window={scrollTo(){},addEventListener:(type,fn)=>listeners.set('window:'+type,fn),setTimeout(fn,delay){let id=++sequence;timers.set(id,{fn,time:now+delay});return id;},clearTimeout:id=>timers.delete(id),PointerEvent:function(){}};
 const document={hidden:false,visibilityState:'visible',getElementById:node,querySelectorAll:selector=>selector==='#ploSeats .plo-card'?[...nodes.values()].filter(n=>/^plo-h-\d-\d$/.test(n.id)):screens,createElement:tag=>node('created-'+(++sequence)),addEventListener:(type,fn)=>listeners.set('document:'+type,fn)};
 const context=vm.createContext({AbortController,fetch:options.fetch||(()=>Promise.reject(new TypeError('offline'))),crypto:{randomUUID:require('node:crypto').randomUUID,getRandomValues(values){values[0]=options.randomValue??0;return values;}},clearTimeout:window.clearTimeout,window,document,navigator:{maxTouchPoints:options.maxTouchPoints??5},localStorage,performance:{now:()=>now},console});
 vm.runInContext(source,context);
 const run=s=>vm.runInContext(s,context);
 function advance(ms) { const target=now+ms; for(let count=0;count<1000;count++){ const next=[...timers].filter(([,v])=>v.time<=target).sort((a,b)=>a[1].time-b[1].time)[0];if(!next){now=target;return;}now=next[1].time;timers.delete(next[0]);next[1].fn();}throw Error('Timer loop'); }
 function event(id,type,values={}){const fn=listeners.get(id+':'+type);assert.ok(fn,`Missing event binding ${id}:${type}`);fn({preventDefault(){},stopPropagation(){},pointerType:'touch',pointerId:1,clientX:100,clientY:100,...values});}
 return {run,node,advance,event,document,active:id=>node('screen-'+id).classList.contains('active')};
}
test('player count stays within 2–8 and HTML names are escaped',()=>{const a=app();a.run('for(let i=0;i<20;i++)addPlayer();');assert.equal(a.run('players.length'),8);a.run('for(let i=0;i<20;i++)removePlayer(0);');assert.equal(a.run('players.length'),2);a.run('players[0].name=\'<img src=x onerror="alert(1)">\';renderSetup();goToLobby();');assert.match(a.node('playersStrip').innerHTML,/&lt;img/);assert.doesNotMatch(a.node('playersStrip').innerHTML,/<img/);});
test('croc snap reset and back cancel old elimination',()=>{for(const action of ['resetCroc()','goBack()']){const a=app();a.run('startCroc();croc.started=true;croc.badIdx=0;clickTooth(0);'+action);a.advance(5000);assert.equal(a.run('loserName'),'');assert.ok(a.active(action==='goBack()'?'lobby':'croc'));}});
test('rapid croc taps cannot consume next player turn',()=>{const a=app();a.run('startCroc();croc.started=true;croc.badIdx=14;clickTooth(0);clickTooth(1);');assert.equal(a.run('croc.pulled.size'),1);a.advance(220);a.run('clickTooth(1)');assert.equal(a.run('croc.pulled.size'),2);});
test('reaction back and restart cancels old countdown and restores prompt',()=>{const a=app();a.run('startReaction();onReactionTap()');a.advance(600);a.run('goBack();startReaction()');a.advance(5000);assert.equal(a.run('rxn.phase'),'idle');assert.equal(a.node('reactionBig').textContent,'Tap to Start');});
test('reaction false start beats any valid slow time and double taps record once',()=>{const a=app();a.run('players=[{name:"Early"},{name:"Slow"}];startReaction();onReactionTap();onReactionTap();onReactionTap();');assert.equal(a.run('rxn.scores.length'),1);a.advance(1800);a.run('rxn.phase="green";rxn.goTime=performance.now()-5000;onReactionTap()');a.advance(5000);assert.equal(a.run('loserName'),'');assert.ok(a.active('reaction'));a.run('continueReaction()');assert.equal(a.run('loserName'),'Early');});
test('tied slowest players replay; duplicate names retain player identity',()=>{const a=app();a.run('players=[{name:"Same"},{name:"Same"},{name:"Fast"}];startReaction();rxn.scores=[{player:0,name:"Same",ms:500,label:"500ms"},{player:1,name:"Same",ms:500,label:"500ms"},{player:2,name:"Fast",ms:100,label:"100ms"}];endReaction()');a.advance(10000);assert.equal(a.run('rxn.phase'),'done-all');a.run('continueReaction()');assert.equal(a.run('JSON.stringify(rxn.contestants)'),'[0,1]');assert.equal(a.run('loserName'),'');assert.equal(a.run('rxn.phase'),'idle');});
test('cards rank and suit resolve correctly; repeated flip is idempotent',()=>{const a=app();a.run('players=[{name:"Ace"},{name:"Club"},{name:"Heart"}];startCards();cards.hands[0].card={r:"A",s:"♣"};cards.hands[1].card={r:"2",s:"♣"};cards.hands[2].card={r:"2",s:"♥"};flipCard(0);flipCard(0);');assert.equal(a.run('cards.flippedCount'),1);a.run('flipCard(1);flipCard(2)');a.advance(3000);assert.equal(a.run('loserName'),'Club');a.run('showFinalResult()');assert.equal(a.node('finalName').textContent,'Club');});
test('cards back cancels both resolution and delayed elimination',()=>{for(const delay of [0,1000]){const a=app();a.run('startCards();flipCard(0);flipCard(1);flipCard(2)');a.advance(delay);a.run('goBack()');a.advance(5000);assert.ok(a.active('lobby'));assert.equal(a.run('loserName'),'');}});
test('malformed remembered players safely defaults; valid names restore',()=>{assert.equal(app({'whopays-players':'[null]'}).run('players.length'),3);assert.equal(app({'whopays-players':'["Leo","Sam"]'}).run('pname(1)'),'Sam');});
test('croc starting seat is randomized across full player range',()=>{for(const [random,expected] of [[0,0],[0.999999,7]]){const a=app();a.run('players=Array.from({length:8},(_,i)=>({name:"Guest "+i}));Math.random=()=>'+random+';startCroc()');assert.equal(a.run('croc.currentPlayer'),expected);assert.equal(a.node('crocTurnName').textContent,'Guest '+expected);}});
test('add player visibly disables at maximum and re-enables after removal',()=>{const a=app();a.run('while(players.length<8)addPlayer()');assert.equal(a.node('addPlayerBtn').disabled,true);assert.match(a.node('addPlayerBtn').textContent,/8/);a.run('removePlayer(0)');assert.equal(a.node('addPlayerBtn').disabled,false);});
test('all-player reaction tie retains tiebreak label throughout replay',()=>{const a=app();a.run('players=[{name:"A"},{name:"B"}];startReaction();rxn.scores=[{player:0,name:"A",ms:Infinity,label:"EARLY"},{player:1,name:"B",ms:Infinity,label:"EARLY"}];endReaction();continueReaction()');assert.match(a.node('reactionRoundLabel').textContent,/Tiebreak/);a.run('onReactionTap();onReactionTap()');a.advance(1800);assert.match(a.node('reactionRoundLabel').textContent,/Tiebreak/);assert.equal(a.run('rxn.playerIdx'),1);});
test('stale reaction Continue cannot leave lobby or overwrite winner',()=>{const a=app();a.run('startReaction();rxn.scores=[{player:0,name:"A",ms:500,label:"500ms"}];endReaction();goBack();continueReaction()');assert.ok(a.active('lobby'));assert.equal(a.run('loserName'),'');});
function fingers(a,count){for(let id=1;id<=count;id++)a.event('fingerPad','pointerdown',{pointerId:id,clientX:30+id*30});}
test('finger mode waits for full roster, restarts countdown on changed membership',()=>{const a=app();a.run('startFinger()');fingers(a,2);a.advance(5000);assert.equal(a.run('finger.phase'),'waiting');a.event('fingerPad','pointerdown',{pointerId:3});a.advance(1500);a.event('fingerPad','pointercancel',{pointerId:3});a.advance(1000);assert.equal(a.run('finger.phase'),'waiting');a.event('fingerPad','pointerdown',{pointerId:4});a.advance(5999);assert.equal(a.run('finger.phase'),'countdown');a.advance(1);assert.equal(a.run('finger.phase'),'chosen');});
test('extra fingers cancel countdown until exactly one per player remains',()=>{const a=app();a.run('startFinger()');fingers(a,3);a.advance(1500);a.event('fingerPad','pointerdown',{pointerId:4});a.advance(1000);assert.equal(a.run('finger.phase'),'waiting');a.event('fingerPad','pointerup',{pointerId:4});a.advance(5999);assert.equal(a.run('finger.phase'),'countdown');a.advance(1);assert.equal(a.run('finger.phase'),'chosen');});
test('selected finger freezes; name confirmation waits for every finger release',()=>{const a=app({}, {randomValue:1});a.run('startFinger()');fingers(a,3);a.advance(6000);assert.equal(a.run('finger.chosen'),2);a.run('confirmFinger(2)');assert.ok(a.active('finger'));assert.equal(a.run('loserName'),'');a.event('fingerPad','pointermove',{pointerId:2,clientX:200});assert.equal(a.run('finger.points.get(2).x'),90);a.event('fingerPad','pointerdown',{pointerId:4});assert.equal(a.run('finger.points.size'),3);for(let id=1;id<=3;id++)a.event('fingerPad','pointerup',{pointerId:id});assert.equal(a.node('fingerIdentity').hidden,false);assert.equal(a.run('finger.chosen'),2);a.run('confirmFinger(99)');assert.ok(a.active('finger'));a.run('confirmFinger(2)');assert.ok(a.active('finger'));assert.equal(a.run('finger.expected'),2);assert.equal(a.run('JSON.stringify(finger.safe)'),'[2]');assert.equal(a.run('loserName'),'');a.run('confirmFinger(1)');assert.equal(a.run('finger.expected'),2);});
test('finger reset, navigation and background cancel pending picks',()=>{for(const action of ['resetFinger()','goBack()','hidden']){const a=app();a.run('startFinger()');fingers(a,3);a.advance(1500);if(action==='hidden'){a.document.hidden=true;a.event('document','visibilitychange');}else a.run(action);a.advance(5000);assert.notEqual(a.run('finger.phase'),'chosen');assert.equal(a.run('finger.points.size'),0);assert.equal(a.run('loserName'),'');if(action==='goBack()')assert.ok(a.active('lobby'));}});
test('finger ignores mouse, duplicate contacts and devices below roster capacity',()=>{const a=app();a.run('startFinger()');a.event('fingerPad','pointerdown',{pointerType:'mouse'});assert.equal(a.run('finger.points.size'),0);fingers(a,3);fingers(a,3);assert.equal(a.run('finger.points.size'),3);const b=app({}, {maxTouchPoints:2});b.run('startFinger()');fingers(b,3);b.advance(7000);assert.equal(b.run('finger.active'),false);assert.equal(b.run('finger.points.size'),0);assert.match(b.node('fingerSupport').textContent,/maximum of 2/);});
test('finger supports eight participants when device supports eight touches',()=>{const a=app({}, {maxTouchPoints:8,randomValue:7});a.run('while(players.length<8)addPlayer();startFinger()');fingers(a,8);a.advance(6000);assert.equal(a.run('finger.chosen'),8);assert.equal(a.run('finger.phase'),'chosen');});
test('finger moving outside pad or losing capture removes contact and cancels pick',()=>{for(const [type,values] of [['pointermove',{clientX:400}],['lostpointercapture',{}]]){const a=app();a.run('startFinger()');fingers(a,3);a.advance(1500);a.event('fingerPad',type,{pointerId:2,...values});a.advance(1000);assert.equal(a.run('finger.phase'),'waiting');assert.equal(a.run('finger.points.size'),2);}});
test('finger resize cancels a held countdown; stale reset cannot reactivate outside mode',()=>{const a=app();a.run('startFinger()');fingers(a,3);a.advance(1500);a.event('window','resize');a.advance(7000);assert.equal(a.run('finger.phase'),'waiting');assert.equal(a.run('finger.points.size'),0);a.run('goBack();resetFinger()');fingers(a,3);a.advance(7000);assert.equal(a.run('finger.active'),false);assert.ok(a.active('lobby'));});

// PLO fixtures use distinct physical cards; exactly two hole and three board cards.
function pokerCards(text) {const ranks='23456789TJQKA',suits='cdhs';return text.split(' ').map(c=>({rank:ranks.indexOf(c[0])+2,suit:suits.indexOf(c[1])}));}
function evaluate(a,hole,board){return JSON.parse(a.run('JSON.stringify(ploEvaluate('+JSON.stringify(pokerCards(hole))+','+JSON.stringify(pokerCards(board))+'))'));}
test('PLO recognizes all nine hand categories with exactly two plus three',()=>{const a=app();const cases=[
 ['Ac Qd 3h 2s','Kh Jc 9d 7s 4h',0],
 ['Ac Ad 3h 2s','Kh Jc 9d 7s 4h',1],
 ['Ac Kd 3h 2s','Ah Kc 9d 7s 4h',2],
 ['Ac Ad 3h 2s','Ah Kc 9d 7s 4h',3],
 ['Ac Kd 3h 2s','Qh Jc Td 7s 4h',4],
 ['Ac Qc 3h 2s','Kc Jc 9c 7s 4h',5],
 ['Ac Ad 3h 2s','Ah Kc Kd 7s 4h',6],
 ['Ac Ad 3h 2s','Ah As Kd 7s 4h',7],
 ['Ac Kc 3h 2s','Qc Jc Tc 7s 4h',8]];
 for(const [hole,board,category] of cases){const result=evaluate(a,hole,board);assert.equal(result.score[0],category,hole+' / '+board);assert.equal(result.cards.length,5);}
});
test('PLO cannot play a board royal flush or use only one suited hole card',()=>{const a=app();assert.equal(evaluate(a,'2d 3h 4s 5d','Ac Kc Qc Jc Tc').score[0],0);assert.notEqual(evaluate(a,'Ac Kd 3h 2s','Qc Jc 9c 7c 4h').score[0],5);});
test('PLO wheel ranks five high and loses to six-high straight',()=>{const a=app();const wheel=evaluate(a,'Ac 2d Kh Qh','3s 4c 5d 9h Ts');const six=evaluate(a,'2c 6d Kh Qh','3s 4c 5d 9h Ts');assert.deepEqual(wheel.score,[4,5]);assert.deepEqual(six.score,[4,6]);assert.ok(a.run('ploCompare('+JSON.stringify(six.score)+','+JSON.stringify(wheel.score)+')')>0);});
test('PLO full house prioritizes trips; quads prioritize kicker; suits do not break ties',()=>{const a=app();const compare=(x,y)=>a.run('ploCompare('+JSON.stringify(x.score)+','+JSON.stringify(y.score)+')');
 assert.ok(compare(evaluate(a,'Ac Ad 3h 2s','Ah Kc Kd 7s 4h'),evaluate(a,'Kc Kd 3h 2s','Kh Ac Ad 7s 4h'))>0);
 assert.ok(compare(evaluate(a,'Ac Kd 3h 2s','Ah As Ad 7s 4h'),evaluate(a,'Ac Qd 3h 2s','Ah As Ad 7s 4h'))>0);
 assert.equal(compare(evaluate(a,'Ac Kd 3h 2s','Qh Jc Td 7s 4h'),evaluate(a,'Ad Ks 3c 2h','Qh Jc Td 7s 4h')),0);
});
test('PLO shuffled deck contains all 52 physical cards exactly once',()=>{const a=app();const deck=JSON.parse(a.run('JSON.stringify(ploShuffle())'));assert.equal(deck.length,52);assert.equal(new Set(deck.map(c=>c.rank+':'+c.suit)).size,52);assert.ok(deck.every(c=>c.rank>=2&&c.rank<=14&&c.suit>=0&&c.suit<=3));});

test('PLO five-heart board still needs two heart hole cards; board trips need a hole pair for full house',()=>{const a=app();assert.notEqual(evaluate(a,'Ah Kd 3c 2s','Qh Jh 9h 7h 4h').score[0],5);assert.equal(evaluate(a,'Ac Kd 3h 2s','9h 9c 9d 7s 4h').score[0],3);});

test('PLO same-category kickers compare lexicographically',()=>{const a=app();const cases=[[[0,14,13,11,9,7],[0,14,13,11,9,6]],[[1,10,14,8,6],[1,10,14,8,5]],[[2,12,8,14],[2,12,8,13]],[[3,9,14,8],[3,9,14,7]],[[5,14,12,9,7,4],[5,14,12,9,7,3]],[[6,10,8],[6,10,7]]];for(const [hi,lo] of cases){assert.ok(a.run('ploCompare('+JSON.stringify(hi)+','+JSON.stringify(lo)+')')>0);assert.ok(a.run('ploCompare('+JSON.stringify(lo)+','+JSON.stringify(hi)+')')<0);}});

function beginPoker(a,n){a.run('startPlo()');a.node('ploCount').value=String(n);a.run('dealPlo()');}
function revealAllPoker(a,n){for(let i=0;i<n;i++)for(let c=0;c<4;c++)a.run(`revealPlo(${i},${c})`);}
test('PLO two and eight seats get four unique hidden cards each plus unique five-card board',()=>{for(const n of [2,8]){const a=app();beginPoker(a,n);const state=JSON.parse(a.run('JSON.stringify(plo)'));assert.equal(state.hands.length,n);assert.ok(state.hands.every(h=>h.length===4));assert.equal(state.board.length,5);const all=[...state.hands.flat(),...state.board];assert.equal(new Set(all.map(c=>c.rank+':'+c.suit)).size,n*4+5);assert.equal(state.count,0);assert.ok(state.revealed.flat().every(x=>!x));a.run('revealPlo(0,0);finishPlo()');assert.equal(a.run('plo.count'),0);a.advance(12000);assert.equal(a.run('plo.phase'),'reveal');assert.equal(a.run('plo.count'),0);assert.equal(a.node('plo-h-0-0').disabled,false);assert.doesNotMatch(a.node('ploStatus').textContent,/wins|Shared win/);}});
test('PLO repeated tap reveals only one; winner waits for every card and final flip',()=>{const a=app();beginPoker(a,2);a.advance(12000);a.run('revealPlo(0,0);revealPlo(0,0)');assert.equal(a.run('plo.count'),1);for(let i=0;i<2;i++)for(let c=0;c<4;c++)if(i!==1||c!==3)a.run(`revealPlo(${i},${c})`);a.advance(1000);assert.equal(a.run('plo.phase'),'reveal');assert.equal(a.run('plo.count'),7);a.run('revealPlo(1,3)');assert.equal(a.run('plo.phase'),'settling');a.advance(449);assert.equal(a.run('plo.phase'),'settling');a.advance(1);assert.equal(a.run('plo.phase'),'finished');assert.match(a.node('ploStatus').textContent,/pays/);});
test('PLO navigation and new hand cancel deal, runout and final resolution timers',()=>{for(const delay of [0,2000,12000])for(const action of ['goBack()','startPlo()']){const a=app();beginPoker(a,2);a.advance(delay);if(delay===12000)revealAllPoker(a,2);a.run(action);const status=a.node('ploStatus').textContent;a.advance(20000);assert.equal(a.node('ploStatus').textContent,status);if(action==='goBack()')assert.ok(a.active('lobby'));else assert.equal(a.run('plo.phase'),'setup');}});
test('PLO shared winners are announced together, with no arbitrary suit tiebreak',()=>{const a=app();beginPoker(a,2);a.advance(12000);a.run('plo.hands='+JSON.stringify([pokerCards('Ac Kd 3h 2s'),pokerCards('Ad Ks 3c 2h')])+';plo.board='+JSON.stringify(pokerCards('Qh Jc Td 7s 4h')));revealAllPoker(a,2);a.advance(450);assert.match(a.node('ploStatus').textContent,/Shared win/);assert.equal(a.node('plo-seat-0').classList.contains('winner'),true);assert.equal(a.node('plo-seat-1').classList.contains('winner'),true);});
test('finger movement retains marker identity and gentle pulse when everyone joins',()=>{const a=app();a.run('startFinger()');fingers(a,3);const first=a.node('fingerMarkers').children.find(n=>n.dataset.pointer==='1');a.event('fingerPad','pointermove',{pointerId:1,clientX:170});assert.equal(a.node('fingerMarkers').children.find(n=>n.dataset.pointer==='1'),first);assert.equal(first.className,'finger-marker');assert.equal(first.style.left,'170px');});
test('PLO ignores duplicate deal, malformed reveal and stale actions outside poker',()=>{const a=app();beginPoker(a,2);const hands=a.run('JSON.stringify(plo.hands)');a.run('dealPlo()');assert.equal(a.run('JSON.stringify(plo.hands)'),hands);a.advance(12000);a.run('revealPlo(0,0.5);revealPlo(0.5,0);revealPlo(99,0);revealPlo(0,-1)');assert.equal(a.run('plo.count'),0);revealAllPoker(a,2);a.run('goBack();finishPlo();dealPlo();revealPlo(0,0)');a.advance(10000);assert.ok(a.active('lobby'));assert.notEqual(a.run('plo.phase'),'showdown');});

test('leaderboard parses exact cents and rejects negatives, exponents, excess precision',()=>{const a=app();for(const [s,n] of [['0',0],['24.50',2450],['0.01',1],['1000000',100000000]])assert.equal(a.run('scoreCents('+JSON.stringify(s)+')'),n);for(const s of ['-1','1e3','1.001','NaN','Infinity','1000000.01',''])assert.throws(()=>a.run('scoreCents('+JSON.stringify(s)+')'));});
test('leaderboard captures every participant once and final screen does not duplicate',()=>{const a=app();a.run('players=[{name:"A"},{name:"B"}];showElim("A","","Card Draw","");showFinalResult();showFinalResult()');assert.equal(a.run('scoreDrafts.length'),1);assert.equal(a.run('JSON.stringify(scoreDrafts[0].entries.map(e=>e.outcome))'),'["loss","win"]');});
test('leaderboard queues multiple results and restores them after refresh',()=>{const saved={};const a=app(saved);a.run('showElim(pname(0),"","Croc Roulette","");showElim(pname(1),"","Finger Pick","")');const b=app(saved);assert.equal(b.run('scoreDrafts.length'),2);assert.equal(b.run('scoreDinner'),a.run('scoreDinner'));});
test('leaderboard save rejects duplicate normalized names before any request',async()=>{let calls=0;const a=app({}, {fetch:async()=>{calls++;}});a.run('scoreKey="a".repeat(64);players=[{name:"Leo"},{name:" leo "}];showElim("Leo","","Card Draw","");openScoreRecord()');a.node('score-name-0').value='Leo';a.node('score-name-1').value=' leo ';a.node('score-cents-0').value='20';await a.run('saveScoreRound()');assert.equal(calls,0);assert.match(a.node('scoreRecordStatus').textContent,/share a name/);});
test('leaderboard concurrent taps make one request and repeated saves stay idempotent',async()=>{let calls=0,release;const a=app({}, {fetch:()=>{calls++;return new Promise(r=>release=r);}});a.run('scoreKey="a".repeat(64);players=[{name:"A"},{name:"B"}];showElim("A","","Card Draw","");openScoreRecord()');a.node('score-name-0').value='A';a.node('score-name-1').value='B';a.node('score-cents-0').value='24.50';const first=a.run('saveScoreRound()');await a.run('saveScoreRound()');assert.equal(calls,1);release({ok:true,json:async()=>({saved:true})});await first;await a.run('saveScoreRound()');assert.equal(calls,1);assert.equal(a.run('scoreDrafts[0].entries[0].cents'),2450);});
test('leaderboard uncertain network failure freezes payload for identical retry',async()=>{const payloads=[];let fail=true;const a=app({}, {fetch:async(url,o)=>{payloads.push(o.body);if(fail){fail=false;throw new TypeError('offline');}return {ok:true,json:async()=>({saved:true})};}});a.run('scoreKey="a".repeat(64);players=[{name:"A"},{name:"B"}];showElim("A","","Card Draw","");openScoreRecord()');a.node('score-name-0').value='A';a.node('score-name-1').value='B';a.node('score-cents-0').value='20';await a.run('saveScoreRound()');a.node('score-cents-0').value='500';await a.run('saveScoreRound()');assert.equal(payloads.length,2);assert.equal(payloads[0],payloads[1]);});
test('PLO all-player split replays without recording a result',()=>{const a=app();beginPoker(a,2);a.advance(12000);a.run('plo.hands='+JSON.stringify([pokerCards('Ac Kd 3h 2s'),pokerCards('Ad Ks 3c 2h')])+';plo.board='+JSON.stringify(pokerCards('Qh Jc Td 7s 4h')));revealAllPoker(a,2);a.advance(450);assert.equal(a.run('scoreDrafts.length'),0);assert.equal(a.run('plo.remaining.length'),2);a.run('advancePlo()');assert.equal(a.run('plo.names.length'),2);});
test('leaderboard preserves losing seat even with identical names',()=>{const a=app();a.run('players=[{name:"Sam"},{name:"Sam"}];showElim("Sam","","Card Draw","",1)');assert.equal(a.run('JSON.stringify(scoreDrafts[0].entries.map(e=>e.outcome))'),'["win","loss"]');});

function finishSafePick(a,count,seat){fingers(a,count);a.advance(5999);assert.equal(a.run('finger.phase'),'countdown');assert.doesNotMatch(a.node('fingerStatus').textContent,/\d/);a.advance(1);assert.equal(a.run('finger.phase'),'chosen');for(let i=1;i<=count;i++)a.event('fingerPad','pointerup',{pointerId:i});a.run('confirmFinger('+seat+')');}
test('four-player Finger Pick takes three safe selections and records one final loss',()=>{const a=app();a.run('players=[{name:"A"},{name:"B"},{name:"C"},{name:"D"}];startFinger()');finishSafePick(a,4,2);assert.equal(a.run('finger.expected'),3);assert.equal(a.run('scoreDrafts.length'),0);assert.doesNotMatch(a.node('fingerNames').innerHTML,/confirmFinger\(2\)/);finishSafePick(a,3,0);assert.equal(a.run('finger.expected'),2);assert.match(a.node('fingerSafe').textContent,/C, A/);assert.equal(a.run('scoreDrafts.length'),0);finishSafePick(a,2,3);assert.ok(a.active('elim'));assert.equal(a.run('loserName'),'B');assert.equal(a.run('scoreDrafts.length'),1);assert.equal(a.run('JSON.stringify(scoreDrafts[0].entries.map(e=>e.outcome))'),'["win","loss","win","win"]');a.run('confirmFinger(1)');assert.equal(a.run('scoreDrafts.length'),1);});
test('safe players survive interrupted holds; explicit restart restores full roster',()=>{const a=app();a.run('startFinger()');finishSafePick(a,3,1);fingers(a,2);a.advance(3000);a.document.hidden=true;a.event('document','visibilitychange');a.advance(7000);assert.equal(a.run('finger.expected'),2);assert.equal(a.run('JSON.stringify(finger.safe)'),'[1]');assert.equal(a.run('finger.phase'),'waiting');a.run('resetFinger(true)');assert.equal(a.run('finger.expected'),3);assert.equal(a.run('finger.safe.length'),0);assert.equal(a.run('scoreDrafts.length'),0);});
test('two players need one safe pick; restarting via lobby clears prior progress',()=>{const a=app();a.run('players=[{name:"Same"},{name:"Same"}];startFinger()');finishSafePick(a,2,0);assert.equal(a.run('JSON.stringify(scoreDrafts[0].entries.map(e=>e.outcome))'),'["win","loss"]');a.run('startFinger()');assert.equal(a.run('finger.expected'),2);assert.equal(a.run('finger.safe.length'),0);});

function setPokerFinish(a,hands){a.run('plo.hands='+JSON.stringify(hands.map(pokerCards))+';plo.board='+JSON.stringify(pokerCards('Qh Jc Td 7s 4h')));revealAllPoker(a,hands.length);a.advance(450);}
test('four-player PLO eliminates best hand each round and saves only one final loser',()=>{const a=app();a.run('players=[{name:"A"},{name:"B"},{name:"C"},{name:"D"}]');beginPoker(a,4);a.advance(12000);setPokerFinish(a,['Ac Kd 2h 3s','9c 9d 2c 3d','8c 8d 2s 3h','6c 6d 5h 5s']);assert.equal(a.run('JSON.stringify(plo.remaining)'),'[1,2,3]');assert.equal(a.run('scoreDrafts.length'),0);a.run('advancePlo();advancePlo()');assert.equal(a.run('JSON.stringify(plo.names)'),'["B","C","D"]');a.advance(12000);setPokerFinish(a,['Ac Kd 2h 3s','9c 9d 2c 3d','8c 8d 2s 3h']);assert.equal(a.run('scoreDrafts.length'),0);a.run('advancePlo()');a.advance(12000);setPokerFinish(a,['Ac Kd 2h 3s','9c 9d 2c 3d']);assert.equal(a.run('plo.phase'),'finished');assert.match(a.node('ploStatus').textContent,/D.*pays/);assert.equal(a.run('JSON.stringify(scoreDrafts[0].entries.map(e=>e.outcome))'),'["win","win","win","loss"]');a.run('finishPlo();dealPlo()');assert.equal(a.run('scoreDrafts.length'),1);a.run('advancePlo()');assert.equal(a.run('plo.phase'),'setup');});
test('tied best PLO hands become safe together, preserving duplicate-name seat identity',()=>{const a=app();a.run('players=[{name:"Same"},{name:"Same"},{name:"Last"}]');beginPoker(a,3);a.advance(12000);setPokerFinish(a,['Ac Kd 2h 3s','Ad Ks 2c 3d','9c 9d 2s 3h']);assert.equal(a.run('JSON.stringify(plo.safe)'),'[0,1]');assert.equal(a.run('JSON.stringify(plo.remaining)'),'[2]');assert.equal(a.run('plo.phase'),'finished');assert.equal(a.run('scoreDrafts[0].entries.length'),3);});
test('PLO abandoning a later hand cancels callbacks and records no partial result',()=>{const a=app();beginPoker(a,3);a.advance(12000);setPokerFinish(a,['Ac Kd 2h 3s','9c 9d 2c 3d','8c 8d 2s 3h']);a.run('advancePlo();goBack()');a.advance(20000);assert.equal(a.run('scoreDrafts.length'),0);assert.ok(a.active('lobby'));a.run('startPlo()');assert.equal(a.run('plo.phase'),'setup');});
