// Independent state/timer regression checks. Browser/layout checks run separately.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
function app(saved={},options={}) {
 let now=0, sequence=0; const timers=new Map(), nodes=new Map(), listeners=new Map();
 function node(id) { if(!nodes.has(id)) { const classes=new Set(), attributes=new Map(); const element={style:{setProperty(k,v){this[k]=v;}},dataset:{},children:[],value:id==='teethSlider'?'15':'',textContent:'',innerHTML:'',disabled:false,
 classList:{add:(...cs)=>cs.forEach(c=>classes.add(c)),remove:(...cs)=>cs.forEach(c=>classes.delete(c)),contains:c=>classes.has(c),toggle(c,force){if(force??!classes.has(c)){classes.add(c);return true;}classes.delete(c);return false;}},
 setAttribute:(k,v)=>attributes.set(k,String(v)),getAttribute:k=>attributes.get(k),removeAttribute:k=>attributes.delete(k),
 querySelector:()=>node(id+'-child'),querySelectorAll:()=>[],appendChild(child){this.children.push(child);child.parentNode=this;return child;},append(child){this.appendChild(child);},replaceChildren(...children){this.children=children;},remove(){this.removed=true;},
 addEventListener(type,fn){listeners.set(id+':'+type,fn);},setPointerCapture(){},releasePointerCapture(){},hasPointerCapture(){return true;},getBoundingClientRect:()=>({left:0,top:0,width:360,height:480,right:360,bottom:480}),focus(){}};nodes.set(id,element); } return nodes.get(id); }
 const screens=['setup','lobby','croc','reaction','cards','finger','elim','result'].map(x=>node('screen-'+x));
 const localStorage={getItem:k=>saved[k]??null,setItem:(k,v)=>saved[k]=v};
 const window={scrollTo(){},addEventListener:(type,fn)=>listeners.set('window:'+type,fn),setTimeout(fn,delay){let id=++sequence;timers.set(id,{fn,time:now+delay});return id;},clearTimeout:id=>timers.delete(id),PointerEvent:function(){}};
 const document={hidden:false,visibilityState:'visible',getElementById:node,querySelectorAll:()=>screens,createElement:tag=>node('created-'+(++sequence)),addEventListener:(type,fn)=>listeners.set('document:'+type,fn)};
 const context=vm.createContext({crypto:{getRandomValues(values){values[0]=options.randomValue??0;return values;}},clearTimeout:window.clearTimeout,window,document,navigator:{maxTouchPoints:options.maxTouchPoints??5},localStorage,performance:{now:()=>now},console});
 vm.runInContext(source,context);
 const run=s=>vm.runInContext(s,context);
 function advance(ms) { const target=now+ms; for(let count=0;count<1000;count++){ const next=[...timers].filter(([,v])=>v.time<=target).sort((a,b)=>a[1].time-b[1].time)[0];if(!next){now=target;return;}now=next[1].time;timers.delete(next[0]);next[1].fn();}throw Error('Timer loop'); }
 function event(id,type,values={}){const fn=listeners.get(id+':'+type);assert.ok(fn,`Missing event binding ${id}:${type}`);fn({preventDefault(){},stopPropagation(){},pointerType:'touch',pointerId:1,clientX:100,clientY:100,...values});}
 return {run,node,advance,event,document,active:id=>node('screen-'+id).classList.contains('active')};
}
test('player count stays within 2–8 and HTML names are escaped',()=>{const a=app();a.run('for(let i=0;i<20;i++)addPlayer();');assert.equal(a.run('players.length'),8);a.run('for(let i=0;i<20;i++)removePlayer(0);');assert.equal(a.run('players.length'),2);a.run('players[0].name=\'<img src=x onerror="alert(1)">\';renderSetup();goToLobby();');assert.match(a.node('playersStrip').innerHTML,/&lt;img/);assert.doesNotMatch(a.node('playersStrip').innerHTML,/<img/);});
test('croc snap reset and back cancel old elimination',()=>{for(const action of ['resetCroc()','goBack()']){const a=app();a.run('startCroc();croc.started=true;croc.badIdx=0;clickTooth(0);'+action);a.advance(5000);assert.equal(a.run('loserName'),'');assert.ok(a.active(action==='goBack()'?'lobby':'croc'));}});
test('rapid croc taps cannot consume next player turn',()=>{const a=app();a.run('startCroc();croc.started=true;croc.badIdx=14;clickTooth(0);clickTooth(1);');assert.equal(a.run('croc.pulled.size'),1);a.advance(220);a.run('clickTooth(1)');assert.equal(a.run('croc.pulled.size'),2);});
test('reaction back and restart cancels old countdown and restores prompt',()=>{const a=app();a.run('startReaction();onReactionTap()');a.advance(600);a.run('goBack();startReaction()');a.advance(5000);assert.equal(a.run('rxn.phase'),'idle');assert.equal(a.node('reactionBig').textContent,'Tap to Start');});
test('reaction false start beats any valid slow time and double taps record once',()=>{const a=app();a.run('players=[{name:"Early"},{name:"Slow"}];startReaction();onReactionTap();onReactionTap();onReactionTap();');assert.equal(a.run('rxn.scores.length'),1);a.advance(1800);a.run('rxn.phase="green";rxn.goTime=performance.now()-5000;onReactionTap()');a.advance(5000);assert.equal(a.run('loserName'),'');assert.ok(a.active('reaction'));a.run('continueReaction()');assert.equal(a.run('loserName'),'Early');});
test('tied slowest players replay; duplicate names retain player identity',()=>{const a=app();a.run('players=[{name:"Same"},{name:"Same"},{name:"Fast"}];startReaction();rxn.scores=[{player:0,name:"Same",ms:500,label:"500ms"},{player:1,name:"Same",ms:500,label:"500ms"},{player:2,name:"Fast",ms:100,label:"100ms"}];endReaction()');a.advance(10000);assert.equal(a.run('rxn.phase'),'done-all');a.run('continueReaction()');assert.equal(a.run('JSON.stringify(rxn.contestants)'),'[0,1]');assert.equal(a.run('loserName'),'');assert.equal(a.run('rxn.phase'),'idle');});
test('cards rank and suit resolve correctly; repeated flip is idempotent',()=>{const a=app();a.run('players=[{name:"Ace"},{name:"Club"},{name:"Heart"}];startCards();cards.hands[0].card={r:"A",s:"♣"};cards.hands[1].card={r:"2",s:"♣"};cards.hands[2].card={r:"2",s:"♥"};flipCard(0);flipCard(0);');assert.equal(a.run('cards.flippedCount'),1);a.run('flipCard(1);flipCard(2)');a.advance(3000);assert.equal(a.run('loserName'),'Club');a.run('showFinalResult()');assert.equal(a.node('finalName').textContent,'Club');});
test('cards back cancels both resolution and delayed elimination',()=>{for(const delay of [0,1000]){const a=app();a.run('startCards();flipCard(0);flipCard(1);flipCard(2)');a.advance(delay);a.run('goBack()');a.advance(5000);assert.ok(a.active('lobby'));assert.equal(a.run('loserName'),'');}});
test('malformed remembered players safely defaults; valid names restore',()=>{assert.equal(app({'whopays-players':'[null]'}).run('players.length'),3);assert.equal(app({'whopays-players':'["Leo","Sam"]'}).run('pname(1)'),'Sam');});
test('croc starting seat is randomized across full player range',()=>{for(const [random,expected] of [[0,0],[0.999999,7]]){const a=app();a.run('players=Array.from({length:8},(_,i)=>({name:"Guest "+i}));Math.random=()=>'+random+';startCroc()');assert.equal(a.run('croc.currentPlayer'),expected);assert.equal(a.node('crocTurnName').textContent,'Guest '+expected);}});
test('add player visibly disables at maximum and re-enables after removal',()=>{const a=app();a.run('while(players.length<8)addPlayer()');assert.equal(a.node('addPlayerBtn').disabled,true);assert.match(a.node('addPlayerBtn').textContent,/8/);a.run('removePlayer(0)');assert.equal(a.node('addPlayerBtn').disabled,false);});
test('all-player reaction tie retains tiebreak label throughout replay',()=>{const a=app();a.run('players=[{name:"A"},{name:"B"}];startReaction();rxn.scores=[{player:0,name:"A",ms:Infinity,label:"EARLY"},{player:1,name:"B",ms:Infinity,label:"EARLY"}];endReaction();continueReaction()');assert.match(a.node('reactionRoundLabel').textContent,/Tiebreak/);a.run('onReactionTap();onReactionTap()');a.advance(1800);assert.match(a.node('reactionRoundLabel').textContent,/Tiebreak/);assert.equal(a.run('rxn.playerIdx'),1);});
test('stale reaction Continue cannot leave lobby or overwrite winner',()=>{const a=app();a.run('startReaction();rxn.scores=[{player:0,name:"A",ms:500,label:"500ms"}];endReaction();goBack();continueReaction()');assert.ok(a.active('lobby'));assert.equal(a.run('loserName'),'');});
function fingers(a,count){for(let id=1;id<=count;id++)a.event('fingerPad','pointerdown',{pointerId:id,clientX:30+id*30});}
test('finger mode waits for full roster, restarts countdown on changed membership',()=>{const a=app();a.run('startFinger()');fingers(a,2);a.advance(5000);assert.equal(a.run('finger.phase'),'waiting');a.event('fingerPad','pointerdown',{pointerId:3});a.advance(1500);a.event('fingerPad','pointercancel',{pointerId:3});a.advance(1000);assert.equal(a.run('finger.phase'),'waiting');a.event('fingerPad','pointerdown',{pointerId:4});a.advance(1999);assert.equal(a.run('finger.phase'),'countdown');a.advance(1);assert.equal(a.run('finger.phase'),'chosen');});
test('extra fingers cancel countdown until exactly one per player remains',()=>{const a=app();a.run('startFinger()');fingers(a,3);a.advance(1500);a.event('fingerPad','pointerdown',{pointerId:4});a.advance(1000);assert.equal(a.run('finger.phase'),'waiting');a.event('fingerPad','pointerup',{pointerId:4});a.advance(1999);assert.equal(a.run('finger.phase'),'countdown');a.advance(1);assert.equal(a.run('finger.phase'),'chosen');});
test('selected finger freezes; name confirmation waits for every finger release',()=>{const a=app({}, {randomValue:1});a.run('startFinger()');fingers(a,3);a.advance(2000);assert.equal(a.run('finger.chosen'),2);a.run('confirmFinger(2)');assert.ok(a.active('finger'));assert.equal(a.run('loserName'),'');a.event('fingerPad','pointermove',{pointerId:2,clientX:200});assert.equal(a.run('finger.points.get(2).x'),90);a.event('fingerPad','pointerdown',{pointerId:4});assert.equal(a.run('finger.points.size'),3);for(let id=1;id<=3;id++)a.event('fingerPad','pointerup',{pointerId:id});assert.equal(a.node('fingerIdentity').hidden,false);assert.equal(a.run('finger.chosen'),2);a.run('confirmFinger(99)');assert.ok(a.active('finger'));a.run('confirmFinger(2)');assert.ok(a.active('elim'));assert.equal(a.run('loserName'),a.run('pname(2)'));a.run('confirmFinger(1)');assert.equal(a.run('loserName'),a.run('pname(2)'));});
test('finger reset, navigation and background cancel pending picks',()=>{for(const action of ['resetFinger()','goBack()','hidden']){const a=app();a.run('startFinger()');fingers(a,3);a.advance(1500);if(action==='hidden'){a.document.hidden=true;a.event('document','visibilitychange');}else a.run(action);a.advance(5000);assert.notEqual(a.run('finger.phase'),'chosen');assert.equal(a.run('finger.points.size'),0);assert.equal(a.run('loserName'),'');if(action==='goBack()')assert.ok(a.active('lobby'));}});
test('finger ignores mouse, duplicate contacts and devices below roster capacity',()=>{const a=app();a.run('startFinger()');a.event('fingerPad','pointerdown',{pointerType:'mouse'});assert.equal(a.run('finger.points.size'),0);fingers(a,3);fingers(a,3);assert.equal(a.run('finger.points.size'),3);const b=app({}, {maxTouchPoints:2});b.run('startFinger()');fingers(b,3);b.advance(3000);assert.equal(b.run('finger.active'),false);assert.equal(b.run('finger.points.size'),0);assert.match(b.node('fingerSupport').textContent,/maximum of 2/);});
test('finger supports eight participants when device supports eight touches',()=>{const a=app({}, {maxTouchPoints:8,randomValue:7});a.run('while(players.length<8)addPlayer();startFinger()');fingers(a,8);a.advance(2000);assert.equal(a.run('finger.chosen'),8);assert.equal(a.run('finger.phase'),'chosen');});
test('finger moving outside pad or losing capture removes contact and cancels pick',()=>{for(const [type,values] of [['pointermove',{clientX:400}],['lostpointercapture',{}]]){const a=app();a.run('startFinger()');fingers(a,3);a.advance(1500);a.event('fingerPad',type,{pointerId:2,...values});a.advance(1000);assert.equal(a.run('finger.phase'),'waiting');assert.equal(a.run('finger.points.size'),2);}});
test('finger resize cancels a held countdown; stale reset cannot reactivate outside mode',()=>{const a=app();a.run('startFinger()');fingers(a,3);a.advance(1500);a.event('window','resize');a.advance(3000);assert.equal(a.run('finger.phase'),'waiting');assert.equal(a.run('finger.points.size'),0);a.run('goBack();resetFinger()');fingers(a,3);a.advance(3000);assert.equal(a.run('finger.active'),false);assert.ok(a.active('lobby'));});
